### ISSUE TITLE
你好 我编译出了问题

### ISSUE THREAD

**Issue by luketalk** [Twinzo1/openwrt#1]
make -r package/openwrt/dogcom_openwrt/compile: build failed. Please re-run make with -j1 V=s to see what's going on
make: *** [package/openwrt/dogcom_openwrt/compile] Error 1

用的oramips-mt7620 的 这个

**Comment by Twinzo1** [comment]
make compile -j1 V=s 试一下，看看是什么问题

**Comment by Twinzo1** [comment]
可以换不更新版，这个我一直在更新，可能会有bug

**Comment by luketalk** [comment]
好的 谢谢
