### ISSUE TITLE
手机连接断网

### ISSUE THREAD

**Issue by luketalk** [Twinzo1/openwrt#2]
你好 我用的dogcom_1.6.5-3_mipsel_24kc.ipk  5.2.1D 版本
只要是手机连接wifi就会断网过段时间就会断网
开启了防代理 用的是privoxy 照着https://www.right.com.cn/forum/thread-249325-1-1.html 这个修改的  是我的设置问题还是学校的问题？ 
求指导
![image](https://user-images.githubusercontent.com/12665953/57541356-63920480-7381-11e9-90e4-d9a937120591.png)
![image](https://user-images.githubusercontent.com/12665953/57541371-6b51a900-7381-11e9-87c6-803f5a657c07.png)

**Comment by Twinzo1** [comment]
我用的是P版，也不清楚你们学校防代理检测方法。开了防代理设置后就不需要设置手动防火墙了，直接开启代理即可。可能修改UA并不是必要的步骤，所以我用了tinyproxy代理。建议绑定ip/mac，需要上网的设备，再给其通过代理的权限

**Comment by luketalk** [comment]
![image](https://user-images.githubusercontent.com/12665953/57577608-786bb680-74ad-11e9-91fc-8b8f779c2568.png)
![image](https://user-images.githubusercontent.com/12665953/57577611-802b5b00-74ad-11e9-98f8-df9258761130.png)
你好 我这么设置对吗？
绑定 IP mac 我没有找到地方

**Comment by Twinzo1** [comment]
你的设置是对的，允许连接端口不需要设置，默认即可。
ip/mac绑定，直接找ipk包安装或直接将文件拖进路由器，搜arpbind

**Comment by luketalk** [comment]
你好 现在不断网了
但出现了一种情况 
在电脑运行腾讯手游模拟器时

**Comment by luketalk** [comment]
不论手机还是电脑只要运行q就会断网
