### ISSUE TITLE
这个能放进路由器里面吗？

### ISSUE THREAD

**Issue by ghost** [Twinzo1/openwrt#3]
刷了个openwrt的固件，怎么把它装进去？

**Comment by Twinzo1** [comment]
你是说哪个
有两种方法：
1、安装ipk包，可以参照我给的链接修改（不用编译，随便找个ipk包修改即可）
2、winscp直接放进相应目录

**Comment by ghost** [comment]
逛了逛论坛，搞明白了，回头尝试一下，非常感谢
